### PR TITLE
Rename readme. to readme.md

### PR DESCRIPTION
**Pull request by Nandan9911**

### CODE REVIEW

**Comment by Nandan9911** [comment]
Hello ma'am, Please delete or rename this file as it is a duplicate and has incorrect extension. Thanks, Nandan

**Comment by Nandan9911** [comment]
The pull request from mu local is failing due to the incorrect name.

**Comment by Nandan9911** [comment]
closing

**Comment by Kiranwaghmare123** [comment]
Thanks for update.

**Pull request closed without merging**
